import java.io.File;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(new File("src/main/resources/gates.js"));
            int lineNumber = 1;
            while (scanner.hasNextLine()){
                String line = scanner.nextLine();
                if (
                    line == "" ||
                    line.endsWith("{") ||
                    line.endsWith("}") ||
                    line.contains("if") ||
                    line.contains("else")
                ) {
                } else {
                    throw new Exception("There was an error on line: " + lineNumber);
                }
                lineNumber++;
            }
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
}
