import java.io.File;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(new File("src/main/resources/gates.js"));
            scanFile(scanner);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }

    public static void scanFile(Scanner file){
        try {
            int lineNumber = 1;
            while (file.hasNextLine()){
                String line = file.nextLine();
                if (
                        line.endsWith(";") ||
                        line == "" ||
                        line.endsWith("{") ||
                        line.endsWith("}") ||
                        line.contains("if") ||
                        line.contains("else")
                ) {
                } else {
                    System.out.println("There was an error on line " + lineNumber + ": Missing semicolon.");
                }
                lineNumber++;
            }
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
}
