/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.io.File;
import java.util.Scanner;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testScanTest1() {
        App app = new App();
        try {
            Scanner scanner = new Scanner(new File("src/test/resources/test1.js"));
            app.scanFile(scanner);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    @Test public void testScanTest2() {
        App app = new App();
        try {
            Scanner scanner = new Scanner(new File("src/test/resources/test2.js"));
            app.scanFile(scanner);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    @Test public void testScanTest3() {
        App app = new App();
        try {
            Scanner scanner = new Scanner(new File("src/test/resources/test3.js"));
            app.scanFile(scanner);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    @Test public void testScanTest4() {
        App app = new App();
        try {
            Scanner scanner = new Scanner(new File("src/test/resources/test4.js"));
            app.scanFile(scanner);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    @Test public void testScanTest5() {
        App app = new App();
        try {
            Scanner scanner = new Scanner(new File("src/test/resources/test5.js"));
            app.scanFile(scanner);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
