import java.util.HashSet;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public int[] roll(int num){
        Random random = new Random();
        int[] rolls = new int[num];
        for (int dice : rolls){
            dice = random.nextInt(6) + 1;
        }
        return rolls;
    }

    public boolean containsDuplicates (int[] array){
        HashSet hash = new HashSet();
        boolean hasDupes = false;
        for (int num : array){
            hasDupes = hash.add(num) ? hasDupes : true;
        }
        return hasDupes;
    }

    public float calcAvg(int[] array){
        int dividend = 0;
        int divisor = array.length;
        float quotient = 0;
        for (int num : array){
            dividend += num;
        }
        quotient = (float) dividend / divisor;
        return quotient;
    }

    public int[] lowestArrayAvg(int[][] nested){
        if (nested[0].length < 2){
            return nested[0];
        }
        int[] lowestArr = nested[0];
        float low = calcAvg(nested[0]);
        for (int[] inner : nested){
            float curr = calcAvg(inner);
            if (curr < low){
                low = curr;
                lowestArr = inner;
            }
        }
        return lowestArr;
    }
}
